name: Comment on Failed Job

on:
  workflow_run:
    workflows: ["$default"]
    types:
      - completed

jobs:
  comment_on_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the workflow failed
        id: check_workflow_status
        run: echo ::set-output name=failed::$(if [ ${{ github.event.workflow_run.conclusion }} == 'failure' ]; then echo "true"; else echo "false"; fi)

      - name: Comment on failure
        if: steps.check_workflow_status.outputs.failed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const message = `Hey @${{ github.event.workflow_run.head_commit.author.login }}, looks like the code check failed. Could you run pnpm format:fix and push again?`;
            github.issues.createComment({
              issue_number: ${{ github.event.workflow_run.head_commit.id }},
              owner: '${{ github.event.repository.owner.login }}',
              repo: '${{ github.event.repository.name }}',
              body: message
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
